id: A6B690DA6
title: ยง16
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:44:16.098400
  last_modified_at: 2022-03-01 21:44:16.098406
