id: A6B690DA6
title: ยง18
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:44:16.101698
  last_modified_at: 2022-03-01 21:44:16.101702
