id: A6B690DA6
title: ยง8
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:44:16.109891
  last_modified_at: 2022-03-01 21:44:16.109893
